### ISSUE TITLE
Getting error when using POST in express

### ISSUE THREAD

**Issue by vnistor** [SocketCluster/iocluster#2]
I receive notifications from an external service to a POST route in express. That executes some code. Weirdly, when this code completes, I get errors in totally unrelated parts of the application. They seem to be comming from iocluster.

Can a POST to express interact with what socketcluster is doing?

https://gist.github.com/vnistor/a26092823205f714b9e3

**Comment by jondubois** [comment]
@vnistor No it shouldn't. Express is just installed by default but it's optional. You can remove express entirely and SC should still work.

It looks like `scServer.global.publish()` is being called - Maybe you are calling it from inside the HTTP POST handler?

The publish behavior does make use of iocluster to make sure that the messages are passed to all subscribers on all workers but this isn't coupled to express iself.

**Comment by jondubois** [comment]
Can you reproduce the issue consistently?
In /node_modules/sc/cleanup/node_modules/socketcluster/node_modules/iocluster/clientcluster.js directly above line 97, can you add the following:

```
console.log('KEYS:', Object.keys(activeClients[i]));
```

Things worth trying:
Update SocketCluster to the latest version (this should update IOCluster too). Remember to update socketcluster-client too and copy the latest client script (socketcluster-client/socketcluster.js) into your public directory.

**Comment by vnistor** [comment]
@jondubois 
The issue happens every single time.
The thing is, I'm not calling the `scServer.global.publish()` from within the POST hadler. the bitcoin function doesn't contain any refference to SC.

app.post('/webhooks', function(req, res) {
    res.sendStatus(200);
        bitcoin(req.body.hash, req.body.walletId);
    });

The error happens in a totally different part of the code. I have some code which is called when the worker starts. That code just does a setInterval to run a function to get some data from an API. Upon getting the data from the external API, I do some math on it and then call `scServer.global.publish(channel, data)`. This works up until I get a POST in express.

I am running the latest versions of both client and server. 

KEYS is actually empty the time before the error.

KEYS: []
1438645799322 - Origin: Worker (PID 22372)
    [Error] TypeError: Cannot read property 'apply' of undefined
    at EventEmitter.self.(anonymous function) [as publish](/node_modules/sc/cleanup/node_modules/socketcluster/node_modules/iocluster/clientcluster.js:98:46)
    at EventEmitter.IOClusterClient.publish (/node_modules/sc/cleanup/node_modules/socketcluster/node_modules/iocluster/index.js:618:30)
    at EventEmitter.Global.publish (/node_modules/sc/cleanup/node_modules/socketcluster/node_modules/iocluster/index.js:169:25)
    at KrakenClient.<anonymous> (/node_modules/sc/cleanup/lib/big.js:112:29)
    at Request._callback (/node_modules/sc/cleanup/node_modules/kraken-api/kraken.js:151:15)
    at Request.self.callback (/node_modules/sc/cleanup/node_modules/request/request.js:198:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/node_modules/sc/cleanup/node_modules/request/request.js:1057:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/node_modules/sc/cleanup/node_modules/request/request.js:1003:12)
1438645799338 - Origin: Broker (PID 22370)
    [Error] Error: read ECONNRESET
    at exports._errnoException (util.js:746:11)
    at Pipe.onread (net.js:550:26)
1438645799340 - Worker 0 exited - Exit code: 0

It prints this the other times:
KEYS: [ 'socketPath',
  'port',
  'host',
  '_errorDomain',
  '_timeout',
  '_subMap',
  '_commandMap',
  '_pendingActions',
  '_socket',
  '_connecting',
  '_connected',
  '_curID',
  'MAX_ID',
  '_maxListeners',
  '_genID',
  '_execPending',
  '_getAllChannels',
  '_resubscribeAll',
  '_connectHandler',
  '_connect',
  '_exec',
  'isConnected',
  'extractKeys',
  'extractValues',
  'subscribe',
  'unsubscribe',
  'subscriptions',
  'isSubscribed',
  'publish',
  'set',
  'expire',
  'unexpire',
  'getExpiry',
  'add',
  'concat',
  'get',
  'getRange',
  'getAll',
  'count',
  '_stringifyQuery',
  'registerDeathQuery',
  'run',
  'query',
  'remove',
  'removeRange',
  'removeAll',
  'splice',
  'pop',
  'hasKey',
  'end',
  '_events',
  'domain',
  'id' ]

**Comment by jondubois** [comment]
For the record: This issue occurred because Array.prototype was extended and that broke `for ... in` loops which are not safeguarded against this.
